global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'flask-app'
    static_configs:
      - targets: ['app:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 10s

  # Monitoramento do PostgreSQL (se postgres_exporter for adicionado)
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgresql:5432']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: '/metrics'

  # Monitoramento do Nginx (se nginx-prometheus-exporter for adicionado)  
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: '/metrics'
